Avoid exception if team info is not present
ueberauth/ueberauth_slack pull request #10
Opened 2016-07-24 20:56 UTC by bklang

2016-12-03 21:44 UTC, doomspork requested changes
Thank you @bklang, one small change and we can merge.

2016-12-03 21:44 UTC, doomspork commented on lib/ueberauth/strategy/slack.ex
> +        team: Dict.get(conn.private, :slack_team)
This should be `Map.get/3`.

2016-12-04 19:17 UTC, scrogson commented on lib/ueberauth/strategy/slack.ex
> +        team: Dict.get(conn.private, :slack_team)
These could actually all be turned into `conn.private[:slack_*]`.

The square bracket access will just return `nil` for missing keys.

2016-12-09 16:37 UTC, doomspork commented on lib/ueberauth/strategy/slack.ex
> +        team: Dict.get(conn.private, :slack_team)
@bklang could you incorporate @scrogson's feedback?

2016-12-12 16:23 UTC, bklang commented
Sorry, was traveling last week. I'll have a look at this based on the feedback.

2016-12-12 16:23 UTC, bklang commented on lib/ueberauth/strategy/slack.ex
> +        team: Dict.get(conn.private, :slack_team)
Sorry, was traveling last week. I'll have a look at this based on the feedback.

2016-12-12 21:51 UTC, doomspork commented on lib/ueberauth/strategy/slack.ex
> +        team: Dict.get(conn.private, :slack_team)
@bklang no worries, I was as well.  Thanks again for contributing your fix.

2016-12-12 23:51 UTC, bklang commented
Updated per code review and rebased

2016-12-15 17:45 UTC, doomspork commented
Thank you @bklang 👍

2016-12-15 17:45 UTC, doomspork approved these changes

2016-12-15 17:45 UTC, merged