Enable configurable redirect_uri
ueberauth/ueberauth_slack pull request #26
Opened 2018-02-27 13:44 UTC by alvincrespo

I'm currently using this lib in a JSON based API. The single page app (SPA) set's a `redirect_uri` that is a route to the SPA instead of the API so that the UI can do some other requests. This library currently assumes the `redirect_uri` is relative to the SPA, which doesn't fit my current use case.

The change here is to allow the developer to specify this redirect_uri from a config Keyword list.

## Changes

- Checks for redirect_uri key in the `Ueberauth ` config
  - if it exists, we use that value
  - if it does not exist, we use the default from client_options

## Question

- Should this redirect_uri be configurable on `config :ueberauth, Ueberauth.Strategy.Slack.OAuth` or `config :ueberauth, Ueberauth`?

2018-02-27 13:48 UTC, alvincrespo commented
@doomspork Curious what your thoughts are here?

PS. Not sure if you're the person to ping here, if not please point me in the right direction.

2018-02-27 21:49 UTC, alvincrespo commented
I moved this to the slack strategy so that it's easier to read - I think this is the place it probably belonged first.

2018-03-17 15:08 UTC, doomspork commented
Sorry for the delays @alvincrespo, I've been away.  For future reference, there is a @ueberauth/developers team you can ping 😁

2018-03-17 15:09 UTC, doomspork requested changes

2018-03-17 15:09 UTC, doomspork commented on lib/ueberauth/strategy/slack.ex
> +    redirect_uri = conn |> get_redirect_uri
Please don't use pipes for single function calls, also please use `()` 👍

2018-03-17 15:09 UTC, doomspork commented on lib/ueberauth/strategy/slack.ex
> +    redirect_uri = config |> Keyword.get(:redirect_uri)
No need to pipe this.

2018-03-17 15:09 UTC, doomspork commented on lib/ueberauth/strategy/slack.ex
> +    case is_nil(redirect_uri) do
This should just be an `if`, there's no real matching taking place here.

2018-03-20 00:45 UTC, alvincrespo commented
@doomspork Thanks for the review! @ueberauth/developers Ready for another round of review.

2018-03-20 00:45 UTC, alvincrespo commented
Ah, looks like I don't have access to use @ueberauth/developers handle.

2018-04-24 23:55 UTC, alvincrespo commented
@doomspork Just wanted to see if there was anything I could do to move this forward?

2018-04-25 04:03 UTC, doomspork commented
Thank you @alvincrespo 👍

I will cut ueberauth/guardian releases later this week.  In the meantime you can point to master:

```elixir
{:ueberauth_slack, github: "ueberauth/ueberauth_slack"}
```

2018-04-25 04:04 UTC, merged

2018-04-25 13:13 UTC, alvincrespo commented
@doomspork w00t! Thanks for your help 😄